name: Build
on:
  push:
    branches: "**"
    pull_request: {}


jobs:
  build:
    name: Swift ${{ matrix.swift }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-13
            swift: "6.0"
          - os: macos-14
            swift: "6.0"
          - os: macos-15
            swift: "6.0"
    steps:
    - uses: SwiftyLab/setup-swift@latest
      with:
        swift-version: ${{ matrix.swift }}

    - run: swift --version
    - uses: actions/checkout@v4
    - run: swift build -c release
    - id: release-path
      run: RELEASE_PATH=`swift build  --show-bin-path -c release` >> $GITHUB_OUTPUT
    - uses: actions/upload-artifact@v4
      with:
        name: Release
        path: ${{ steps.release-path.outputs.RELEASE_PATH }}
